/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qgliadwhvzdqqohxvojn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbGlhZHdodnpkcXFvaHh2b2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5Mjk0MjUsImV4cCI6MjA3NzUwNTQyNX0.FcOLTRIBzKi1OiAg-VCgLC-FaJkEBHxeYS4lYaj9p94"